sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qazwsx12300
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAWNX7YMxDJtUDhn73h
    access-key-secret: 4wPT7v0gVODRHkJgLkO1BdzKU148k7
    bucket-name: web-797

  redis:
    host: localhost
    port: 6379
    database: 10
